[package]
name = "rchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
num = "0.4.0"
sha2 = "0.10.6"

[dev-dependencies]
data-encoding = "2.3.3"
